#include "MainWindow.h"

#include <QWidget>
#include <QVBoxLayout>
#include <QPushButton>
#include <QTextEdit>
#include <QLabel>
#include <QtConcurrent>

#include <sstream>
#include <vector>

#include "libnormaliz/cone.h"

using namespace libnormaliz;

MainWindow::MainWindow(QWidget* parent) : QMainWindow(parent) {
    auto* central = new QWidget(this);
    auto* layout = new QVBoxLayout(central);

    layout->addWidget(new QLabel("2cone example - cone generated by rays (1,3) and (2,1)"));

    btn_ = new QPushButton("Compute Hilbert basis", central);
    layout->addWidget(btn_);

    output_ = new QTextEdit(central);
    output_->setReadOnly(true);
    layout->addWidget(output_);

    setCentralWidget(central);
    setWindowTitle("Normaliz GUI (skeleton)");
    resize(520, 400);

    connect(btn_, &QPushButton::clicked, this, &MainWindow::startCompute);
    connect(&watcher_, &QFutureWatcher<Result>::finished, this, &MainWindow::computeFinished);
}

// Worker thread. libnormaliz throws std::exception-derived NormalizException;
// QtConcurrent does not propagate non-QException types safely, so we catch here
// and hand back a plain Result. Nothing may throw past this function.
MainWindow::Result MainWindow::runHilbertBasis() {
    Result r;
    try {
        std::vector<std::vector<mpz_class> > rays;
        rays.push_back(std::vector<mpz_class>{1, 3});
        rays.push_back(std::vector<mpz_class>{2, 1});

        Cone<mpz_class> cone(Type::cone, rays);
        cone.compute(ConeProperty::HilbertBasis);
        const std::vector<std::vector<mpz_class> >& hb = cone.getHilbertBasis();

        std::ostringstream oss;
        oss << hb.size() << " Hilbert basis elements:\n";
        for (const std::vector<mpz_class>& v : hb) {
            for (const mpz_class& x : v) oss << x << " ";
            oss << "\n";
        }
        r.ok = true;
        r.text = oss.str();
    } catch (const std::exception& e) {
        r.text = std::string("Error: ") + e.what();
    } catch (...) {
        r.text = "Error: unknown exception in libnormaliz";
    }
    return r;
}

void MainWindow::startCompute() {
    btn_->setEnabled(false);
    output_->setPlainText("Computing...");
    // Off the GUI thread so a long computation cannot freeze the UI.
    watcher_.setFuture(QtConcurrent::run(&MainWindow::runHilbertBasis));
}

void MainWindow::computeFinished() {
    const Result r = watcher_.result();
    output_->setPlainText(QString::fromStdString(r.text));
    btn_->setEnabled(true);
}
